export type BusinessWorkspaceMode = "advanced_company" | "simple_shop";

export const BUSINESS_TEAM_ASSIGNABLE_ROLES = [
  {
    value: "admin",
    label: "Administrator",
    detail: "Broad operational administration. Only the primary owner can grant this role.",
    privileged: true,
  },
  {
    value: "it_admin",
    label: "IT Administrator",
    detail: "Team access, notifications, branches, and technical operations without financial authority.",
    privileged: true,
  },
  {
    value: "hr_admin",
    label: "HR Administrator",
    detail: "Employees, payroll preparation, documents, and workforce approvals.",
    privileged: true,
  },
  {
    value: "finance",
    label: "Finance Manager",
    detail: "Accounting, banking, tax, budgets, payroll payments, assets, and FX controls.",
    privileged: true,
  },
  {
    value: "accountant",
    label: "Accountant",
    detail: "Accounting, reconciliations, purchases, collections, and financial reporting.",
    privileged: false,
  },
  {
    value: "operations_manager",
    label: "Operations Manager",
    detail: "Cross-functional daily operations, branches, approvals, projects, and inventory.",
    privileged: false,
  },
  {
    value: "manager",
    label: "Manager",
    detail: "Daily team and operational workflows without owner-level controls.",
    privileged: false,
  },
  {
    value: "auditor",
    label: "Auditor",
    detail: "Read-only financial, operational, payroll, tax, document, and audit visibility.",
    privileged: false,
  },
  {
    value: "branch_staff",
    label: "Branch Staff",
    detail: "Branch-scoped sales, stock, customer, and counter workflows.",
    privileged: false,
  },
  {
    value: "employee",
    label: "Employee",
    detail: "Basic documents, notifications, approval requests, and assigned project work.",
    privileged: false,
  },
  {
    value: "sales",
    label: "Sales",
    detail: "Customers, invoices, collections, and CRM workflows.",
    privileged: false,
  },
  {
    value: "cashier",
    label: "Cashier",
    detail: "Payments and approved Simple Shop counter workflows.",
    privileged: false,
  },
  {
    value: "inventory",
    label: "Inventory",
    detail: "Products, stock counts, transfers, and approved adjustments.",
    privileged: false,
  },
  {
    value: "viewer",
    label: "Viewer",
    detail: "General read-only operational and reporting access.",
    privileged: false,
  },
] as const;

export type BusinessTeamRole =
  | "owner"
  | (typeof BUSINESS_TEAM_ASSIGNABLE_ROLES)[number]["value"];

export const BUSINESS_SENSITIVE_PERMISSIONS = new Set([
  "team.manage",
  "notifications.manage",
  "banking.manage",
  "tax.manage",
  "budget.approve",
  "approvals.decide",
  "approvals.manage",
  "payroll.manage",
  "payroll.process",
  "payroll.pay",
  "assets.dispose",
  "fx.revalue",
  "branches.manage",
  "projects.recognize",
]);

export const BUSINESS_PERMISSION_GROUPS = [
  {
    label: "Team & notifications",
    permissions: [
      ["team.view", "View team"],
      ["team.manage", "Manage team"],
      ["notifications.view", "View notifications"],
      ["notifications.manage", "Manage notification rules"],
    ],
  },
  {
    label: "Accounting, banking & tax",
    permissions: [
      ["accounting.view", "View accounting"],
      ["accounting.manage", "Manage accounting"],
      ["banking.view", "View banking"],
      ["banking.manage", "Manage banking and reconciliation"],
      ["tax.view", "View tax"],
      ["tax.manage", "Manage tax"],
      ["reports.view", "View reports"],
    ],
  },
  {
    label: "Budgets & approvals",
    permissions: [
      ["budget.view", "View budgets"],
      ["budget.manage", "Manage budgets"],
      ["budget.approve", "Approve budgets"],
      ["approvals.view", "View approvals"],
      ["approvals.request", "Request approvals"],
      ["approvals.decide", "Decide approvals"],
      ["approvals.manage", "Manage approval policies"],
    ],
  },
  {
    label: "Documents, branches & projects",
    permissions: [
      ["documents.view", "View documents"],
      ["documents.manage", "Manage documents"],
      ["branches.view", "View branches"],
      ["branches.manage", "Manage branches"],
      ["projects.view", "View projects"],
      ["projects.manage", "Manage projects"],
      ["projects.time", "Record project time"],
      ["projects.recognize", "Run project recognition"],
    ],
  },
  {
    label: "Payroll & assets",
    permissions: [
      ["payroll.view", "View payroll"],
      ["payroll.manage", "Manage payroll"],
      ["payroll.process", "Process payroll"],
      ["payroll.pay", "Pay payroll"],
      ["assets.view", "View fixed assets"],
      ["assets.manage", "Manage fixed assets"],
      ["assets.depreciate", "Run depreciation"],
      ["assets.dispose", "Dispose assets"],
    ],
  },
  {
    label: "Foreign exchange",
    permissions: [
      ["fx.view", "View FX"],
      ["fx.manage", "Manage FX rates"],
      ["fx.revalue", "Run FX revaluation"],
    ],
  },
  {
    label: "Contacts, sales & CRM",
    permissions: [
      ["contacts.view", "View contacts"],
      ["contacts.manage", "Manage contacts"],
      ["sales.view", "View sales"],
      ["sales.manage", "Manage sales"],
      ["sales.collect", "Collect payments"],
      ["sales.return", "Process sales returns"],
      ["crm.view", "View CRM"],
      ["crm.manage", "Manage CRM"],
    ],
  },
  {
    label: "Purchases & inventory",
    permissions: [
      ["purchases.view", "View purchases"],
      ["purchases.manage", "Manage purchases"],
      ["purchases.pay", "Pay suppliers"],
      ["purchases.return", "Process purchase returns"],
      ["inventory.view", "View inventory"],
      ["inventory.manage", "Manage products and stock"],
      ["inventory.transfer", "Transfer stock"],
      ["inventory.adjust", "Adjust physical stock"],
    ],
  },
  {
    label: "Simple Shop",
    permissions: [
      ["shop.view", "View shop"],
      ["shop.sell", "Post sales"],
      ["shop.purchase", "Post purchases"],
      ["shop.expense", "Post expenses"],
    ],
  },
] as const;

export type BusinessPermissionGroup = (typeof BUSINESS_PERMISSION_GROUPS)[number];

const ADVANCED_ROLE_TEMPLATES: Record<Exclude<BusinessTeamRole, "owner">, readonly string[]> = {
  admin: BUSINESS_PERMISSION_GROUPS.flatMap((group) =>
    group.permissions.map(([permission]) => permission),
  ),
  it_admin: [
    "team.view",
    "team.manage",
    "notifications.view",
    "notifications.manage",
    "documents.view",
    "documents.manage",
    "branches.view",
    "branches.manage",
  ],
  hr_admin: [
    "team.view",
    "team.manage",
    "notifications.view",
    "documents.view",
    "documents.manage",
    "approvals.view",
    "approvals.request",
    "payroll.view",
    "payroll.manage",
    "payroll.process",
  ],
  finance: [
    "accounting.view",
    "accounting.manage",
    "banking.view",
    "banking.manage",
    "tax.view",
    "tax.manage",
    "budget.view",
    "budget.manage",
    "budget.approve",
    "approvals.view",
    "approvals.decide",
    "payroll.view",
    "payroll.pay",
    "assets.view",
    "assets.manage",
    "assets.depreciate",
    "assets.dispose",
    "fx.view",
    "fx.manage",
    "fx.revalue",
    "purchases.view",
    "purchases.pay",
    "sales.view",
    "sales.collect",
    "reports.view",
  ],
  accountant: [
    "accounting.view",
    "accounting.manage",
    "banking.view",
    "tax.view",
    "budget.view",
    "payroll.view",
    "assets.view",
    "fx.view",
    "purchases.view",
    "purchases.manage",
    "purchases.pay",
    "sales.view",
    "sales.collect",
    "reports.view",
  ],
  operations_manager: [
    "team.view",
    "notifications.view",
    "contacts.view",
    "contacts.manage",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "sales.return",
    "purchases.view",
    "purchases.manage",
    "purchases.return",
    "inventory.view",
    "inventory.manage",
    "inventory.transfer",
    "inventory.adjust",
    "crm.view",
    "crm.manage",
    "documents.view",
    "branches.view",
    "approvals.view",
    "approvals.request",
    "projects.view",
    "projects.manage",
    "projects.time",
    "reports.view",
  ],
  manager: [
    "team.view",
    "notifications.view",
    "contacts.view",
    "contacts.manage",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "purchases.view",
    "purchases.manage",
    "inventory.view",
    "inventory.manage",
    "crm.view",
    "crm.manage",
    "documents.view",
    "branches.view",
    "approvals.view",
    "approvals.request",
    "projects.view",
    "projects.time",
    "reports.view",
  ],
  auditor: [
    "team.view",
    "notifications.view",
    "accounting.view",
    "banking.view",
    "tax.view",
    "budget.view",
    "documents.view",
    "branches.view",
    "approvals.view",
    "payroll.view",
    "assets.view",
    "fx.view",
    "projects.view",
    "contacts.view",
    "sales.view",
    "purchases.view",
    "inventory.view",
    "crm.view",
    "reports.view",
  ],
  branch_staff: [
    "notifications.view",
    "branches.view",
    "contacts.view",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "inventory.view",
    "inventory.transfer",
    "shop.view",
    "shop.sell",
  ],
  employee: [
    "notifications.view",
    "documents.view",
    "approvals.view",
    "approvals.request",
    "projects.view",
    "projects.time",
  ],
  sales: [
    "notifications.view",
    "contacts.view",
    "contacts.manage",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "crm.view",
    "crm.manage",
  ],
  cashier: ["notifications.view", "contacts.view", "sales.view", "sales.collect", "shop.view", "shop.sell"],
  inventory: [
    "notifications.view",
    "purchases.view",
    "inventory.view",
    "inventory.manage",
    "inventory.transfer",
    "inventory.adjust",
    "shop.view",
    "shop.purchase",
  ],
  viewer: [
    "notifications.view",
    "accounting.view",
    "contacts.view",
    "sales.view",
    "purchases.view",
    "inventory.view",
    "crm.view",
    "reports.view",
  ],
};

const SIMPLE_ROLE_TEMPLATES: Record<Exclude<BusinessTeamRole, "owner">, readonly string[]> = {
  ...ADVANCED_ROLE_TEMPLATES,
  admin: [
    "team.view",
    "team.manage",
    "notifications.view",
    "notifications.manage",
    "accounting.view",
    "accounting.manage",
    "contacts.view",
    "contacts.manage",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "sales.return",
    "purchases.view",
    "purchases.manage",
    "purchases.pay",
    "purchases.return",
    "inventory.view",
    "inventory.manage",
    "inventory.transfer",
    "inventory.adjust",
    "reports.view",
    "shop.view",
    "shop.sell",
    "shop.purchase",
    "shop.expense",
  ],
  finance: [
    "accounting.view",
    "accounting.manage",
    "banking.view",
    "banking.manage",
    "purchases.view",
    "purchases.pay",
    "sales.view",
    "sales.collect",
    "reports.view",
    "shop.view",
  ],
  accountant: [
    "accounting.view",
    "accounting.manage",
    "purchases.view",
    "purchases.pay",
    "sales.view",
    "sales.collect",
    "reports.view",
    "shop.view",
  ],
  operations_manager: [
    "team.view",
    "notifications.view",
    "contacts.view",
    "contacts.manage",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "sales.return",
    "purchases.view",
    "purchases.manage",
    "purchases.return",
    "inventory.view",
    "inventory.manage",
    "inventory.transfer",
    "inventory.adjust",
    "reports.view",
    "shop.view",
    "shop.sell",
    "shop.purchase",
    "shop.expense",
  ],
  manager: [
    "team.view",
    "notifications.view",
    "contacts.view",
    "contacts.manage",
    "sales.view",
    "sales.manage",
    "sales.collect",
    "purchases.view",
    "purchases.manage",
    "inventory.view",
    "inventory.manage",
    "reports.view",
    "shop.view",
    "shop.sell",
    "shop.purchase",
    "shop.expense",
  ],
  auditor: [
    "team.view",
    "accounting.view",
    "contacts.view",
    "sales.view",
    "purchases.view",
    "inventory.view",
    "reports.view",
    "shop.view",
  ],
  branch_staff: [
    "notifications.view",
    "contacts.view",
    "sales.view",
    "sales.collect",
    "inventory.view",
    "shop.view",
    "shop.sell",
  ],
  employee: ["notifications.view", "shop.view"],
  sales: ["notifications.view", "contacts.view", "contacts.manage", "sales.view", "sales.manage", "sales.collect", "shop.view", "shop.sell"],
  cashier: ["notifications.view", "shop.view", "shop.sell", "shop.expense"],
  inventory: ["notifications.view", "purchases.view", "inventory.view", "inventory.manage", "inventory.transfer", "inventory.adjust", "shop.view", "shop.purchase"],
  viewer: ["accounting.view", "contacts.view", "sales.view", "purchases.view", "inventory.view", "reports.view", "shop.view"],
};

export function isSensitiveBusinessPermission(value: string) {
  return BUSINESS_SENSITIVE_PERMISSIONS.has(value);
}

export function isPrivilegedBusinessRole(value: string) {
  return BUSINESS_TEAM_ASSIGNABLE_ROLES.some(
    (role) => role.value === value && role.privileged,
  );
}

export function businessRoleLabel(value: string) {
  if (value === "owner") return "Owner";
  return (
    BUSINESS_TEAM_ASSIGNABLE_ROLES.find((role) => role.value === value)?.label ??
    value.replace(/_/g, " ")
  );
}

export function suggestedBusinessPermissions(
  role: string,
  mode: BusinessWorkspaceMode,
) {
  const template =
    mode === "simple_shop" ? SIMPLE_ROLE_TEMPLATES : ADVANCED_ROLE_TEMPLATES;
  return [...(template[role as Exclude<BusinessTeamRole, "owner">] ?? [])];
}

export function visibleBusinessPermissionGroups(mode: BusinessWorkspaceMode) {
  if (mode === "advanced_company") return BUSINESS_PERMISSION_GROUPS;
  const allowed = new Set([
    "Team & notifications",
    "Accounting, banking & tax",
    "Contacts, sales & CRM",
    "Purchases & inventory",
    "Simple Shop",
  ]);
  return BUSINESS_PERMISSION_GROUPS.filter((group) => allowed.has(group.label));
}
