<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Jalvoro.BusinessCore.ContractTests</AssemblyName>
    <RootNamespace>Jalvoro.BusinessCore.ContractTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Jalvoro.BusinessCore.Application\Jalvoro.BusinessCore.Application.csproj" />
    <ProjectReference Include="..\..\src\Jalvoro.BusinessCore.Domain\Jalvoro.BusinessCore.Domain.csproj" />
  </ItemGroup>
</Project>
