begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to service_role;

create extension if not exists pgcrypto with schema extensions;

create table private.control_plane_operators (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null,
  is_root_owner boolean not null default false,
  status text not null default 'active',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  disabled_at timestamptz,
  disabled_by uuid references auth.users(id) on delete set null,
  constraint control_plane_operators_role_check check (
    role in ('owner', 'admin', 'analyst', 'support')
  ),
  constraint control_plane_operators_status_check check (
    status in ('active', 'disabled')
  ),
  constraint control_plane_root_owner_role_check check (
    not is_root_owner or role = 'owner'
  ),
  constraint control_plane_operator_disabled_check check (
    (status = 'disabled' and disabled_at is not null)
    or (status = 'active' and disabled_at is null)
  )
);

create unique index control_plane_single_root_owner_idx
  on private.control_plane_operators (is_root_owner)
  where is_root_owner;

create table private.control_plane_invitations (
  id uuid primary key default gen_random_uuid(),
  invitation_code text not null unique default (
    'CPI-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))
  ),
  token_sha256 bytea not null unique,
  intended_email_sha256 bytea not null,
  intended_email_masked text not null,
  role text not null,
  status text not null default 'pending',
  created_by uuid not null references auth.users(id) on delete restrict,
  accepted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  revoked_at timestamptz,
  constraint control_plane_invitation_code_check check (
    invitation_code ~ '^CPI-[A-F0-9]{12}$'
  ),
  constraint control_plane_invitation_token_hash_check check (
    octet_length(token_sha256) = 32
  ),
  constraint control_plane_invitation_email_hash_check check (
    octet_length(intended_email_sha256) = 32
  ),
  constraint control_plane_invitation_role_check check (
    role in ('admin', 'analyst', 'support')
  ),
  constraint control_plane_invitation_status_check check (
    status in ('pending', 'accepted', 'revoked', 'expired')
  ),
  constraint control_plane_invitation_expiry_check check (
    expires_at > created_at and expires_at <= created_at + interval '7 days'
  )
);

create table private.control_plane_permission_grants (
  id uuid primary key default gen_random_uuid(),
  grant_code text not null unique default (
    'CPG-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))
  ),
  user_id uuid not null references auth.users(id) on delete cascade,
  permission_key text not null,
  product_key text,
  module_key text,
  environment_key text,
  region_key text,
  organization_id uuid,
  data_classification text,
  granted_by uuid not null references auth.users(id) on delete restrict,
  granted_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  revoked_by uuid references auth.users(id) on delete set null,
  constraint control_plane_grant_code_check check (
    grant_code ~ '^CPG-[A-F0-9]{12}$'
  ),
  constraint control_plane_permission_key_check check (
    permission_key ~ '^[a-z][a-z0-9-]*(:[a-z][a-z0-9-]*){2,4}$'
  ),
  constraint control_plane_environment_check check (
    environment_key is null or environment_key in ('development', 'preview', 'production')
  ),
  constraint control_plane_classification_check check (
    data_classification is null
    or data_classification in ('public', 'internal', 'confidential', 'restricted')
  ),
  constraint control_plane_grant_expiry_check check (
    expires_at is null or expires_at > granted_at
  )
);

create unique index control_plane_active_grant_unique_idx
  on private.control_plane_permission_grants (
    user_id,
    permission_key,
    coalesce(product_key, ''),
    coalesce(module_key, ''),
    coalesce(environment_key, ''),
    coalesce(region_key, ''),
    coalesce(organization_id, '00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(data_classification, '')
  )
  where revoked_at is null;

create table private.control_plane_audit_events (
  id bigint generated by default as identity primary key,
  event_code text not null unique default (
    'CPA-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 16))
  ),
  actor_user_id uuid references auth.users(id) on delete set null,
  subject_user_id uuid references auth.users(id) on delete set null,
  invitation_id uuid references private.control_plane_invitations(id) on delete set null,
  grant_id uuid references private.control_plane_permission_grants(id) on delete set null,
  action text not null,
  previous_role text,
  next_role text,
  permission_key text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint control_plane_audit_event_code_check check (
    event_code ~ '^CPA-[A-F0-9]{16}$'
  ),
  constraint control_plane_audit_action_check check (
    action in (
      'root_owner_bootstrapped',
      'invitation_created',
      'invitation_revoked',
      'invitation_accepted',
      'permission_granted',
      'permission_revoked',
      'operator_role_changed',
      'operator_disabled',
      'operator_restored'
    )
  ),
  constraint control_plane_audit_role_check check (
    (previous_role is null or previous_role in ('owner', 'admin', 'analyst', 'support'))
    and (next_role is null or next_role in ('owner', 'admin', 'analyst', 'support'))
  ),
  constraint control_plane_audit_expiry_check check (expires_at > created_at)
);

alter table private.control_plane_operators enable row level security;
alter table private.control_plane_invitations enable row level security;
alter table private.control_plane_permission_grants enable row level security;
alter table private.control_plane_audit_events enable row level security;

revoke all on private.control_plane_operators,
  private.control_plane_invitations,
  private.control_plane_permission_grants,
  private.control_plane_audit_events
  from public, anon, authenticated;
revoke all on sequence private.control_plane_audit_events_id_seq
  from public, anon, authenticated;

grant select, insert, update, delete on private.control_plane_operators,
  private.control_plane_invitations,
  private.control_plane_permission_grants,
  private.control_plane_audit_events
  to service_role;
grant usage, select on sequence private.control_plane_audit_events_id_seq
  to service_role;

create policy control_plane_operators_deny_direct
  on private.control_plane_operators for all to anon, authenticated
  using (false) with check (false);
create policy control_plane_invitations_deny_direct
  on private.control_plane_invitations for all to anon, authenticated
  using (false) with check (false);
create policy control_plane_permission_grants_deny_direct
  on private.control_plane_permission_grants for all to anon, authenticated
  using (false) with check (false);
create policy control_plane_audit_events_deny_direct
  on private.control_plane_audit_events for all to anon, authenticated
  using (false) with check (false);

create index control_plane_operator_role_status_idx
  on private.control_plane_operators (role, status, created_at desc);
create index control_plane_invitation_status_expiry_idx
  on private.control_plane_invitations (status, expires_at, created_at desc);
create index control_plane_grants_user_active_idx
  on private.control_plane_permission_grants (user_id, permission_key, expires_at)
  where revoked_at is null;
create index control_plane_audit_created_idx
  on private.control_plane_audit_events (created_at desc);
create index control_plane_audit_actor_idx
  on private.control_plane_audit_events (actor_user_id, created_at desc)
  where actor_user_id is not null;

create or replace function private.reject_control_plane_audit_mutation()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  raise exception 'control_plane_audit_is_append_only' using errcode = '42501';
end;
$$;

revoke all on function private.reject_control_plane_audit_mutation()
  from public, anon, authenticated;
grant execute on function private.reject_control_plane_audit_mutation()
  to service_role;

create trigger control_plane_audit_append_only
before update or delete on private.control_plane_audit_events
for each row execute function private.reject_control_plane_audit_mutation();

create or replace function private.mask_control_plane_email(p_email text)
returns text
language sql
immutable
strict
set search_path = pg_catalog
as $$
  select case
    when position('@' in p_email) <= 1 then 'hidden'
    else left(split_part(lower(trim(p_email)), '@', 1), 1)
      || repeat('*', greatest(2, least(char_length(split_part(lower(trim(p_email)), '@', 1)) - 1, 6)))
      || '@' || split_part(lower(trim(p_email)), '@', 2)
  end;
$$;

revoke all on function private.mask_control_plane_email(text)
  from public, anon, authenticated;
grant execute on function private.mask_control_plane_email(text)
  to service_role;

create or replace function private.control_plane_user_reference(p_user_id uuid)
returns text
language sql
immutable
strict
set search_path = pg_catalog, extensions
as $$
  select 'CPU-' || upper(substr(
    encode(extensions.digest(convert_to(p_user_id::text, 'UTF8'), 'sha256'), 'hex'),
    1,
    12
  ));
$$;

revoke all on function private.control_plane_user_reference(uuid)
  from public, anon, authenticated;
grant execute on function private.control_plane_user_reference(uuid)
  to service_role;

create or replace function private.require_control_plane_operator(
  p_allowed_roles text[] default null
)
returns text
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_user_id uuid := auth.uid();
  v_aal text := coalesce(auth.jwt()->>'aal', 'aal1');
  v_role text;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  if v_aal <> 'aal2' then
    raise exception 'mfa_verification_required' using errcode = '42501';
  end if;

  select role into v_role
  from private.control_plane_operators
  where user_id = v_user_id
    and status = 'active'
    and disabled_at is null;

  if v_role is null then
    raise exception 'control_plane_access_required' using errcode = '42501';
  end if;

  if p_allowed_roles is not null and not (v_role = any(p_allowed_roles)) then
    raise exception 'control_plane_role_required' using errcode = '42501';
  end if;

  return v_role;
end;
$$;

revoke all on function private.require_control_plane_operator(text[])
  from public, anon;
grant execute on function private.require_control_plane_operator(text[])
  to authenticated, service_role;

create or replace function private.bootstrap_control_plane_root_owner(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_existing_root uuid;
begin
  if not exists (
    select 1 from auth.users
    where id = p_user_id and deleted_at is null
  ) then
    raise exception 'control_plane_owner_user_not_found' using errcode = '22023';
  end if;

  select user_id into v_existing_root
  from private.control_plane_operators
  where is_root_owner
  limit 1;

  if v_existing_root is not null and v_existing_root <> p_user_id then
    raise exception 'control_plane_root_owner_already_exists' using errcode = '23505';
  end if;

  insert into private.control_plane_operators (
    user_id, role, is_root_owner, status, created_by
  ) values (
    p_user_id, 'owner', true, 'active', p_user_id
  )
  on conflict (user_id) do update
  set role = 'owner',
      is_root_owner = true,
      status = 'active',
      disabled_at = null,
      disabled_by = null,
      updated_at = now();

  if not exists (
    select 1 from private.control_plane_audit_events
    where action = 'root_owner_bootstrapped'
      and subject_user_id = p_user_id
  ) then
    insert into private.control_plane_audit_events (
      actor_user_id, subject_user_id, action, next_role
    ) values (
      p_user_id, p_user_id, 'root_owner_bootstrapped', 'owner'
    );
  end if;

  return jsonb_build_object(
    'userReference', private.control_plane_user_reference(p_user_id),
    'role', 'owner',
    'isRootOwner', true,
    'status', 'active'
  );
end;
$$;

revoke all on function private.bootstrap_control_plane_root_owner(uuid)
  from public, anon, authenticated;
grant execute on function private.bootstrap_control_plane_root_owner(uuid)
  to service_role;

create or replace function public.get_my_control_plane_access()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_user_id uuid := auth.uid();
  v_role text;
  v_is_root boolean;
  v_grants jsonb;
begin
  v_role := private.require_control_plane_operator(null);

  select is_root_owner into v_is_root
  from private.control_plane_operators
  where user_id = v_user_id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'grantCode', grant_code,
    'permissionKey', permission_key,
    'productKey', product_key,
    'moduleKey', module_key,
    'environmentKey', environment_key,
    'regionKey', region_key,
    'organizationId', organization_id,
    'dataClassification', data_classification,
    'expiresAt', expires_at
  ) order by granted_at desc), '[]'::jsonb)
  into v_grants
  from private.control_plane_permission_grants
  where user_id = v_user_id
    and revoked_at is null
    and (expires_at is null or expires_at > now());

  return jsonb_build_object(
    'userReference', private.control_plane_user_reference(v_user_id),
    'role', v_role,
    'isRootOwner', coalesce(v_is_root, false),
    'sessionAssurance', 'aal2',
    'grants', v_grants
  );
end;
$$;

revoke all on function public.get_my_control_plane_access()
  from public, anon;
grant execute on function public.get_my_control_plane_access()
  to authenticated;

create or replace function public.create_control_plane_invitation(
  p_email text,
  p_role text,
  p_token_sha256 text,
  p_expires_in_hours integer default 72
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private, extensions
as $$
declare
  v_actor uuid := auth.uid();
  v_email text := lower(trim(coalesce(p_email, '')));
  v_email_hash bytea;
  v_token_hash bytea;
  v_invitation private.control_plane_invitations%rowtype;
begin
  perform private.require_control_plane_operator(array['owner']);

  if char_length(v_email) < 5 or char_length(v_email) > 254
    or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'control_plane_invitation_email_invalid' using errcode = '22023';
  end if;

  if p_role not in ('admin', 'analyst', 'support') then
    raise exception 'control_plane_invitation_role_invalid' using errcode = '22023';
  end if;

  if p_expires_in_hours < 1 or p_expires_in_hours > 168 then
    raise exception 'control_plane_invitation_expiry_invalid' using errcode = '22023';
  end if;

  if p_token_sha256 !~ '^[a-f0-9]{64}$' then
    raise exception 'control_plane_invitation_token_invalid' using errcode = '22023';
  end if;

  v_email_hash := extensions.digest(convert_to(v_email, 'UTF8'), 'sha256');
  v_token_hash := decode(p_token_sha256, 'hex');

  update private.control_plane_invitations
  set status = 'expired'
  where status = 'pending' and expires_at <= now();

  update private.control_plane_invitations
  set status = 'revoked', revoked_at = now()
  where status = 'pending'
    and intended_email_sha256 = v_email_hash;

  insert into private.control_plane_invitations (
    token_sha256,
    intended_email_sha256,
    intended_email_masked,
    role,
    created_by,
    expires_at
  ) values (
    v_token_hash,
    v_email_hash,
    private.mask_control_plane_email(v_email),
    p_role,
    v_actor,
    now() + make_interval(hours => p_expires_in_hours)
  ) returning * into v_invitation;

  insert into private.control_plane_audit_events (
    actor_user_id, invitation_id, action, next_role
  ) values (
    v_actor, v_invitation.id, 'invitation_created', v_invitation.role
  );

  return jsonb_build_object(
    'invitationCode', v_invitation.invitation_code,
    'maskedEmail', v_invitation.intended_email_masked,
    'role', v_invitation.role,
    'expiresAt', v_invitation.expires_at
  );
end;
$$;

revoke all on function public.create_control_plane_invitation(text, text, text, integer)
  from public, anon;
grant execute on function public.create_control_plane_invitation(text, text, text, integer)
  to authenticated;

create or replace function public.accept_control_plane_invitation(
  p_token_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_aal text := coalesce(auth.jwt()->>'aal', 'aal1');
  v_email text;
  v_email_hash bytea;
  v_token_hash bytea;
  v_invitation private.control_plane_invitations%rowtype;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  if v_aal <> 'aal2' then
    raise exception 'mfa_verification_required' using errcode = '42501';
  end if;

  if p_token_sha256 !~ '^[a-f0-9]{64}$' then
    raise exception 'control_plane_invitation_token_invalid' using errcode = '22023';
  end if;

  select lower(trim(email)) into v_email
  from auth.users
  where id = v_user_id
    and deleted_at is null
    and email_confirmed_at is not null;

  if v_email is null or v_email = '' then
    raise exception 'verified_email_required' using errcode = '42501';
  end if;

  if exists (
    select 1 from private.control_plane_operators where user_id = v_user_id
  ) then
    raise exception 'control_plane_operator_already_exists' using errcode = '23505';
  end if;

  v_email_hash := extensions.digest(convert_to(v_email, 'UTF8'), 'sha256');
  v_token_hash := decode(p_token_sha256, 'hex');

  update private.control_plane_invitations
  set status = 'expired'
  where status = 'pending' and expires_at <= now();

  select * into v_invitation
  from private.control_plane_invitations
  where token_sha256 = v_token_hash
    and intended_email_sha256 = v_email_hash
    and status = 'pending'
    and expires_at > now()
  for update;

  if v_invitation.id is null then
    raise exception 'control_plane_invitation_invalid' using errcode = '42501';
  end if;

  insert into private.control_plane_operators (
    user_id, role, is_root_owner, status, created_by
  ) values (
    v_user_id, v_invitation.role, false, 'active', v_invitation.created_by
  );

  update private.control_plane_invitations
  set status = 'accepted',
      accepted_by = v_user_id,
      accepted_at = now()
  where id = v_invitation.id;

  insert into private.control_plane_audit_events (
    actor_user_id, subject_user_id, invitation_id, action, next_role
  ) values (
    v_user_id, v_user_id, v_invitation.id, 'invitation_accepted', v_invitation.role
  );

  return jsonb_build_object(
    'userReference', private.control_plane_user_reference(v_user_id),
    'role', v_invitation.role,
    'status', 'active'
  );
end;
$$;

revoke all on function public.accept_control_plane_invitation(text)
  from public, anon;
grant execute on function public.accept_control_plane_invitation(text)
  to authenticated;

create or replace function public.grant_control_plane_permission(
  p_user_id uuid,
  p_permission_key text,
  p_product_key text default null,
  p_module_key text default null,
  p_environment_key text default null,
  p_region_key text default null,
  p_organization_id uuid default null,
  p_data_classification text default null,
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_grant private.control_plane_permission_grants%rowtype;
begin
  perform private.require_control_plane_operator(array['owner']);

  if not exists (
    select 1 from private.control_plane_operators
    where user_id = p_user_id and status = 'active' and disabled_at is null
  ) then
    raise exception 'control_plane_operator_not_found' using errcode = '22023';
  end if;

  insert into private.control_plane_permission_grants (
    user_id,
    permission_key,
    product_key,
    module_key,
    environment_key,
    region_key,
    organization_id,
    data_classification,
    granted_by,
    expires_at
  ) values (
    p_user_id,
    p_permission_key,
    nullif(trim(p_product_key), ''),
    nullif(trim(p_module_key), ''),
    nullif(trim(p_environment_key), ''),
    nullif(trim(p_region_key), ''),
    p_organization_id,
    nullif(trim(p_data_classification), ''),
    v_actor,
    p_expires_at
  ) returning * into v_grant;

  insert into private.control_plane_audit_events (
    actor_user_id, subject_user_id, grant_id, action, permission_key
  ) values (
    v_actor, p_user_id, v_grant.id, 'permission_granted', v_grant.permission_key
  );

  return jsonb_build_object(
    'grantCode', v_grant.grant_code,
    'userReference', private.control_plane_user_reference(p_user_id),
    'permissionKey', v_grant.permission_key,
    'expiresAt', v_grant.expires_at
  );
end;
$$;

revoke all on function public.grant_control_plane_permission(uuid, text, text, text, text, text, uuid, text, timestamptz)
  from public, anon;
grant execute on function public.grant_control_plane_permission(uuid, text, text, text, text, text, uuid, text, timestamptz)
  to authenticated;

create or replace function public.revoke_control_plane_permission(
  p_grant_code text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_grant private.control_plane_permission_grants%rowtype;
begin
  perform private.require_control_plane_operator(array['owner']);

  select * into v_grant
  from private.control_plane_permission_grants
  where grant_code = p_grant_code
    and revoked_at is null
  for update;

  if v_grant.id is null then
    raise exception 'control_plane_grant_not_found' using errcode = '22023';
  end if;

  update private.control_plane_permission_grants
  set revoked_at = now(), revoked_by = v_actor
  where id = v_grant.id;

  insert into private.control_plane_audit_events (
    actor_user_id, subject_user_id, grant_id, action, permission_key
  ) values (
    v_actor, v_grant.user_id, v_grant.id, 'permission_revoked', v_grant.permission_key
  );

  return jsonb_build_object(
    'grantCode', v_grant.grant_code,
    'status', 'revoked'
  );
end;
$$;

revoke all on function public.revoke_control_plane_permission(text)
  from public, anon;
grant execute on function public.revoke_control_plane_permission(text)
  to authenticated;

create or replace function public.disable_control_plane_operator(
  p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_operator private.control_plane_operators%rowtype;
begin
  perform private.require_control_plane_operator(array['owner']);

  select * into v_operator
  from private.control_plane_operators
  where user_id = p_user_id
  for update;

  if v_operator.user_id is null then
    raise exception 'control_plane_operator_not_found' using errcode = '22023';
  end if;

  if v_operator.is_root_owner then
    raise exception 'root_owner_cannot_be_disabled' using errcode = '42501';
  end if;

  update private.control_plane_operators
  set status = 'disabled',
      disabled_at = now(),
      disabled_by = v_actor,
      updated_at = now()
  where user_id = p_user_id;

  update private.control_plane_permission_grants
  set revoked_at = now(), revoked_by = v_actor
  where user_id = p_user_id and revoked_at is null;

  insert into private.control_plane_audit_events (
    actor_user_id, subject_user_id, action, previous_role
  ) values (
    v_actor, p_user_id, 'operator_disabled', v_operator.role
  );

  return jsonb_build_object(
    'userReference', private.control_plane_user_reference(p_user_id),
    'status', 'disabled'
  );
end;
$$;

revoke all on function public.disable_control_plane_operator(uuid)
  from public, anon;
grant execute on function public.disable_control_plane_operator(uuid)
  to authenticated;

create or replace function public.get_control_plane_directory()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_result jsonb;
begin
  perform private.require_control_plane_operator(array['owner']);

  select jsonb_build_object(
    'operators', coalesce((
      select jsonb_agg(jsonb_build_object(
        'userReference', private.control_plane_user_reference(o.user_id),
        'role', o.role,
        'isRootOwner', o.is_root_owner,
        'status', o.status,
        'createdAt', o.created_at,
        'disabledAt', o.disabled_at
      ) order by o.is_root_owner desc, o.created_at asc)
      from private.control_plane_operators o
    ), '[]'::jsonb),
    'pendingInvitations', coalesce((
      select jsonb_agg(jsonb_build_object(
        'invitationCode', i.invitation_code,
        'maskedEmail', i.intended_email_masked,
        'role', i.role,
        'expiresAt', i.expires_at
      ) order by i.created_at desc)
      from private.control_plane_invitations i
      where i.status = 'pending' and i.expires_at > now()
    ), '[]'::jsonb),
    'activeGrants', coalesce((
      select jsonb_agg(jsonb_build_object(
        'grantCode', g.grant_code,
        'userReference', private.control_plane_user_reference(g.user_id),
        'permissionKey', g.permission_key,
        'productKey', g.product_key,
        'moduleKey', g.module_key,
        'environmentKey', g.environment_key,
        'regionKey', g.region_key,
        'organizationId', g.organization_id,
        'dataClassification', g.data_classification,
        'expiresAt', g.expires_at
      ) order by g.granted_at desc)
      from private.control_plane_permission_grants g
      where g.revoked_at is null
        and (g.expires_at is null or g.expires_at > now())
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.get_control_plane_directory()
  from public, anon;
grant execute on function public.get_control_plane_directory()
  to authenticated;

commit;
