import type { ProductManifestV1 } from "./product-registry";

export const COMMAND_CENTER_PLATFORM_MANIFEST = {
  schemaVersion: "1.0",
  productId: "prd_command_center",
  productKey: "command-center",
  productFamilyKey: "jalvoro-platform",
  categoryKey: "internal-operations",
  name: "JALVORO Command Center",
  description:
    "Central internal administration, analytics, observability, security, billing, support, governance, configuration, and operational-control platform for the JALVORO ecosystem.",
  iconKey: "jalvoro-shield-money",
  lifecycleStatus: "public_release",
  registrationStatus: "active",
  availability: {
    environments: ["development", "preview", "production"],
    countries: ["*"],
    regions: ["global"],
    currencies: ["*"],
    languages: ["*"],
    platforms: ["web"],
  },
  applications: [
    {
      applicationId: "app_command_center_web",
      applicationKey: "command-center-web",
      name: "JALVORO Command Center Web",
      platforms: ["web"],
      currentVersions: ["current"],
    },
  ],
  modules: [
    {
      moduleId: "mod_global_overview",
      moduleKey: "global-overview",
      name: "Global Overview",
      description:
        "Privacy-safe executive operating pulse for users, billing, access, incidents, security, compliance, and release readiness.",
      lifecycleStatus: "public_release",
      enabled: true,
      requiredPermissions: ["command-center:overview:view"],
    },
    {
      moduleId: "mod_global_operations",
      moduleKey: "global-operations",
      name: "Global Operations",
      description:
        "Worldwide product topology, subscription state, regional reach, and privacy-safe platform distribution.",
      lifecycleStatus: "public_release",
      enabled: true,
      requiredPermissions: ["command-center:overview:view"],
    },
    {
      moduleId: "mod_organizations",
      moduleKey: "organizations",
      name: "Organization Operations",
      description:
        "Private organization lifecycle, memberships, tenant-scoped authorization, controlled administrator grants, and append-only audit operations.",
      lifecycleStatus: "public_release",
      enabled: true,
      requiredPermissions: ["command-center:organizations:view"],
    },
    {
      moduleId: "mod_icon_system",
      moduleKey: "icon-system",
      name: "JALVORO Icon System",
      description:
        "Internal design infrastructure and symbol governance for the official JALVORO interface language.",
      lifecycleStatus: "public_release",
      enabled: true,
      requiredPermissions: ["command-center:icons:view"],
    },
  ],
  serviceDependencies: [
    "supabase-admin-snapshot",
    "supabase-global-operations-snapshot",
    "supabase-organization-control-plane",
  ],
  subscriptionPlanKeys: [],
  analyticsMetricKeys: [
    "active-users",
    "billing-segments",
    "privacy-requests",
    "security-posture",
    "product-topology",
    "organization-topology",
    "regional-reach",
    "platform-distribution",
  ],
  eventSchemaKeys: ["admin-audit-event", "organization-audit-event"],
  healthCheckKeys: [
    "command-center-snapshot",
    "organization-control-plane",
  ],
  errorSourceKeys: ["command-center-runtime"],
  featureFlagKeys: [],
  supportCategoryKeys: ["internal-command-center"],
  securityPolicyKeys: [
    "least-privilege",
    "privacy-minimisation",
    "server-authorisation",
    "tenant-isolation",
  ],
  dataGovernance: {
    classification: "restricted",
    retentionDays: 730,
    residencyRegionKeys: ["global-control-plane"],
  },
  ownership: {
    teamKey: "platform-operations",
    documentationReference: "docs/jalvoro-command-center-registry.md",
  },
  admin: {
    requiredPermissions: ["command-center:platform:view"],
    navigation: [
      {
        navigationId: "global-overview",
        moduleKey: "global-overview",
        label: "Global Overview",
        href: "/admin",
        iconKey: "dashboard",
        order: 10,
        requiredPermissions: ["command-center:overview:view"],
        environments: ["development", "preview", "production"],
      },
      {
        navigationId: "global-operations",
        moduleKey: "global-operations",
        label: "Global Operations",
        href: "/admin/global-operations",
        iconKey: "globe",
        order: 20,
        requiredPermissions: ["command-center:overview:view"],
        environments: ["development", "preview", "production"],
      },
      {
        navigationId: "organizations",
        moduleKey: "organizations",
        label: "Organizations",
        href: "/admin/organizations",
        iconKey: "organizations",
        order: 30,
        requiredPermissions: ["command-center:organizations:view"],
        environments: ["development", "preview", "production"],
      },
      {
        navigationId: "icon-system",
        moduleKey: "icon-system",
        label: "Icon System",
        href: "/admin/icon-system",
        iconKey: "grid",
        order: 900,
        requiredPermissions: ["command-center:icons:view"],
        environments: ["development", "preview", "production"],
      },
    ],
  },
} satisfies ProductManifestV1;
