begin;

create table if not exists private.platform_security_incidents (
  id uuid primary key default gen_random_uuid(),
  incident_code text not null unique default (
    'INC-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))
  ),
  category text not null,
  severity text not null,
  status text not null default 'open',
  source text not null,
  source_reference text,
  assigned_to uuid references auth.users(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete restrict,
  acknowledged_by uuid references auth.users(id) on delete set null,
  resolved_by uuid references auth.users(id) on delete set null,
  resolution_code text,
  due_at timestamptz,
  acknowledged_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz,
  constraint platform_security_incidents_code_check check (
    incident_code ~ '^INC-[A-F0-9]{12}$'
  ),
  constraint platform_security_incidents_category_check check (
    category in (
      'access_governance',
      'privacy_deadline',
      'billing_pipeline',
      'availability',
      'data_boundary',
      'retention',
      'manual_review'
    )
  ),
  constraint platform_security_incidents_severity_check check (
    severity in ('low', 'medium', 'high', 'critical')
  ),
  constraint platform_security_incidents_status_check check (
    status in ('open', 'acknowledged', 'investigating', 'monitoring', 'resolved', 'dismissed')
  ),
  constraint platform_security_incidents_source_check check (
    source in ('posture', 'access', 'privacy', 'billing', 'system', 'manual')
  ),
  constraint platform_security_incidents_source_reference_check check (
    source_reference is null
    or source_reference ~ '^(PRV|ADM|AIN|USR)-[A-F0-9]{12}$'
  ),
  constraint platform_security_incidents_resolution_check check (
    (
      status in ('resolved', 'dismissed')
      and resolution_code in (
        'mitigated',
        'false_positive',
        'duplicate',
        'accepted_risk',
        'no_action_required',
        'superseded'
      )
      and resolved_at is not null
      and resolved_by is not null
      and expires_at is not null
    )
    or (
      status not in ('resolved', 'dismissed')
      and resolution_code is null
      and resolved_at is null
      and resolved_by is null
      and expires_at is null
    )
  ),
  constraint platform_security_incidents_acknowledgement_check check (
    (acknowledged_at is null and acknowledged_by is null)
    or (acknowledged_at is not null and acknowledged_by is not null)
  ),
  constraint platform_security_incidents_due_check check (
    due_at is null or due_at > created_at - interval '1 day'
  ),
  constraint platform_security_incidents_expiry_check check (
    expires_at is null or expires_at > resolved_at
  )
);

comment on table private.platform_security_incidents is
  'Structured Admin Panel incident workflow. Stores controlled operational metadata only; no free-text descriptions, raw IP addresses, session replay, user identities, finance content, provider payloads, credentials, or arbitrary JSON.';

create table if not exists private.platform_security_incident_audit (
  id bigint generated by default as identity primary key,
  incident_id uuid not null references private.platform_security_incidents(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  previous_status text,
  next_status text,
  previous_severity text,
  next_severity text,
  previous_assignment uuid references auth.users(id) on delete set null,
  next_assignment uuid references auth.users(id) on delete set null,
  resolution_code text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint platform_security_incident_audit_action_check check (
    action in ('created', 'workflow_updated')
  ),
  constraint platform_security_incident_audit_status_check check (
    previous_status is null or previous_status in ('open', 'acknowledged', 'investigating', 'monitoring', 'resolved', 'dismissed')
  ),
  constraint platform_security_incident_audit_next_status_check check (
    next_status is null or next_status in ('open', 'acknowledged', 'investigating', 'monitoring', 'resolved', 'dismissed')
  ),
  constraint platform_security_incident_audit_previous_severity_check check (
    previous_severity is null or previous_severity in ('low', 'medium', 'high', 'critical')
  ),
  constraint platform_security_incident_audit_next_severity_check check (
    next_severity is null or next_severity in ('low', 'medium', 'high', 'critical')
  ),
  constraint platform_security_incident_audit_resolution_check check (
    resolution_code is null or resolution_code in (
      'mitigated',
      'false_positive',
      'duplicate',
      'accepted_risk',
      'no_action_required',
      'superseded'
    )
  ),
  constraint platform_security_incident_audit_expiry_check check (
    expires_at > created_at
  )
);

comment on table private.platform_security_incident_audit is
  'Structured incident transition audit with 24-month retention. Contains no free text, raw IP, user identity, finance content, credentials, provider payloads, or arbitrary metadata.';

alter table private.platform_security_incidents enable row level security;
alter table private.platform_security_incident_audit enable row level security;

revoke all on private.platform_security_incidents,
  private.platform_security_incident_audit
  from public, anon, authenticated;
revoke all on sequence private.platform_security_incident_audit_id_seq
  from public, anon, authenticated;

drop policy if exists platform_security_incidents_deny_direct
  on private.platform_security_incidents;
create policy platform_security_incidents_deny_direct
  on private.platform_security_incidents
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists platform_security_incident_audit_deny_direct
  on private.platform_security_incident_audit;
create policy platform_security_incident_audit_deny_direct
  on private.platform_security_incident_audit
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.platform_security_incidents,
  private.platform_security_incident_audit
  to service_role;
grant usage, select on sequence private.platform_security_incident_audit_id_seq
  to service_role;

create index if not exists platform_security_incidents_status_severity_idx
  on private.platform_security_incidents (status, severity, due_at, created_at desc);
create index if not exists platform_security_incidents_assigned_idx
  on private.platform_security_incidents (assigned_to, status, created_at desc)
  where assigned_to is not null;
create index if not exists platform_security_incidents_created_by_idx
  on private.platform_security_incidents (created_by, created_at desc);
create index if not exists platform_security_incidents_due_idx
  on private.platform_security_incidents (due_at)
  where due_at is not null and status not in ('resolved', 'dismissed');
create index if not exists platform_security_incidents_expires_idx
  on private.platform_security_incidents (expires_at)
  where expires_at is not null;
create index if not exists platform_security_incident_audit_incident_idx
  on private.platform_security_incident_audit (incident_id, created_at desc);
create index if not exists platform_security_incident_audit_actor_idx
  on private.platform_security_incident_audit (actor_user_id, created_at desc);
create index if not exists platform_security_incident_audit_expires_idx
  on private.platform_security_incident_audit (expires_at);

create or replace function private.create_platform_security_incident(
  p_category text,
  p_severity text,
  p_source text,
  p_source_reference text default null,
  p_due_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_incident private.platform_security_incidents%rowtype;
  v_source_reference text := nullif(upper(trim(coalesce(p_source_reference, ''))), '');
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'incident_operator_access_required' using errcode = '42501';
  end if;

  if p_category not in (
    'access_governance', 'privacy_deadline', 'billing_pipeline',
    'availability', 'data_boundary', 'retention', 'manual_review'
  ) then
    raise exception 'incident_category_invalid' using errcode = '22023';
  end if;

  if p_severity not in ('low', 'medium', 'high', 'critical') then
    raise exception 'incident_severity_invalid' using errcode = '22023';
  end if;

  if p_source not in ('posture', 'access', 'privacy', 'billing', 'system', 'manual') then
    raise exception 'incident_source_invalid' using errcode = '22023';
  end if;

  if v_source_reference is not null
    and v_source_reference !~ '^(PRV|ADM|AIN|USR)-[A-F0-9]{12}$' then
    raise exception 'incident_source_reference_invalid' using errcode = '22023';
  end if;

  if p_due_at is not null
    and (p_due_at <= now() or p_due_at > now() + interval '365 days') then
    raise exception 'incident_due_at_invalid' using errcode = '22023';
  end if;

  insert into private.platform_security_incidents (
    category,
    severity,
    source,
    source_reference,
    assigned_to,
    created_by,
    due_at
  ) values (
    p_category,
    p_severity,
    p_source,
    v_source_reference,
    v_actor,
    v_actor,
    p_due_at
  ) returning * into v_incident;

  insert into private.platform_security_incident_audit (
    incident_id,
    actor_user_id,
    action,
    next_status,
    next_severity,
    next_assignment
  ) values (
    v_incident.id,
    v_actor,
    'created',
    v_incident.status,
    v_incident.severity,
    v_incident.assigned_to
  );

  return jsonb_build_object(
    'incidentCode', v_incident.incident_code,
    'created', true
  );
end;
$$;

create or replace function public.create_platform_security_incident(
  p_category text,
  p_severity text,
  p_source text,
  p_source_reference text default null,
  p_due_at timestamptz default null
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.create_platform_security_incident(
    p_category,
    p_severity,
    p_source,
    p_source_reference,
    p_due_at
  );
$$;

revoke all on function private.create_platform_security_incident(text, text, text, text, timestamptz)
  from public, anon;
grant execute on function private.create_platform_security_incident(text, text, text, text, timestamptz)
  to authenticated;
revoke all on function public.create_platform_security_incident(text, text, text, text, timestamptz)
  from public, anon;
grant execute on function public.create_platform_security_incident(text, text, text, text, timestamptz)
  to authenticated;

create or replace function private.apply_platform_security_incident_workflow(
  p_incident_code text,
  p_status text,
  p_severity text,
  p_due_at timestamptz default null,
  p_assign_to_self boolean default false,
  p_resolution_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_incident private.platform_security_incidents%rowtype;
  v_incident_code text := upper(trim(coalesce(p_incident_code, '')));
  v_resolution_code text := nullif(lower(trim(coalesce(p_resolution_code, ''))), '');
  v_next_assignment uuid;
  v_now timestamptz := now();
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'incident_operator_access_required' using errcode = '42501';
  end if;

  if v_incident_code !~ '^INC-[A-F0-9]{12}$' then
    raise exception 'incident_code_invalid' using errcode = '22023';
  end if;

  select * into v_incident
  from private.platform_security_incidents
  where incident_code = v_incident_code
  for update;

  if not found then
    raise exception 'incident_not_found' using errcode = 'P0002';
  end if;

  if v_incident.status in ('resolved', 'dismissed') then
    raise exception 'incident_closed' using errcode = '22023';
  end if;

  if v_incident.assigned_to is not null
    and v_incident.assigned_to <> v_actor
    and v_actor_role <> 'owner' then
    raise exception 'incident_assigned_elsewhere' using errcode = '42501';
  end if;

  if p_status not in ('open', 'acknowledged', 'investigating', 'monitoring', 'resolved', 'dismissed') then
    raise exception 'incident_status_invalid' using errcode = '22023';
  end if;

  if p_severity not in ('low', 'medium', 'high', 'critical') then
    raise exception 'incident_severity_invalid' using errcode = '22023';
  end if;

  if p_due_at is not null
    and (p_due_at <= v_incident.created_at - interval '1 day'
      or p_due_at > v_now + interval '365 days') then
    raise exception 'incident_due_at_invalid' using errcode = '22023';
  end if;

  if p_status in ('resolved', 'dismissed') then
    if v_resolution_code not in (
      'mitigated', 'false_positive', 'duplicate',
      'accepted_risk', 'no_action_required', 'superseded'
    ) then
      raise exception 'incident_resolution_invalid' using errcode = '22023';
    end if;

    if p_status = 'dismissed'
      and v_incident.severity = 'critical'
      and v_actor_role <> 'owner' then
      raise exception 'critical_incident_owner_required' using errcode = '42501';
    end if;
  elsif v_resolution_code is not null then
    raise exception 'incident_resolution_not_allowed' using errcode = '22023';
  end if;

  v_next_assignment := case
    when p_assign_to_self then v_actor
    else v_incident.assigned_to
  end;

  update private.platform_security_incidents
  set status = p_status,
      severity = p_severity,
      due_at = p_due_at,
      assigned_to = v_next_assignment,
      acknowledged_at = case
        when p_status <> 'open' and acknowledged_at is null then v_now
        else acknowledged_at
      end,
      acknowledged_by = case
        when p_status <> 'open' and acknowledged_by is null then v_actor
        else acknowledged_by
      end,
      resolution_code = case
        when p_status in ('resolved', 'dismissed') then v_resolution_code
        else null
      end,
      resolved_at = case
        when p_status in ('resolved', 'dismissed') then v_now
        else null
      end,
      resolved_by = case
        when p_status in ('resolved', 'dismissed') then v_actor
        else null
      end,
      expires_at = case
        when p_status in ('resolved', 'dismissed') then v_now + interval '24 months'
        else null
      end,
      updated_at = v_now
  where id = v_incident.id;

  insert into private.platform_security_incident_audit (
    incident_id,
    actor_user_id,
    action,
    previous_status,
    next_status,
    previous_severity,
    next_severity,
    previous_assignment,
    next_assignment,
    resolution_code
  ) values (
    v_incident.id,
    v_actor,
    'workflow_updated',
    v_incident.status,
    p_status,
    v_incident.severity,
    p_severity,
    v_incident.assigned_to,
    v_next_assignment,
    case when p_status in ('resolved', 'dismissed') then v_resolution_code else null end
  );

  return jsonb_build_object(
    'incidentCode', v_incident.incident_code,
    'updated', true
  );
end;
$$;

create or replace function public.apply_platform_security_incident_workflow(
  p_incident_code text,
  p_status text,
  p_severity text,
  p_due_at timestamptz default null,
  p_assign_to_self boolean default false,
  p_resolution_code text default null
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.apply_platform_security_incident_workflow(
    p_incident_code,
    p_status,
    p_severity,
    p_due_at,
    p_assign_to_self,
    p_resolution_code
  );
$$;

revoke all on function private.apply_platform_security_incident_workflow(text, text, text, timestamptz, boolean, text)
  from public, anon;
grant execute on function private.apply_platform_security_incident_workflow(text, text, text, timestamptz, boolean, text)
  to authenticated;
revoke all on function public.apply_platform_security_incident_workflow(text, text, text, timestamptz, boolean, text)
  from public, anon;
grant execute on function public.apply_platform_security_incident_workflow(text, text, text, timestamptz, boolean, text)
  to authenticated;

create or replace function private.get_platform_security_incident_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'operationsAllowed', v_actor_role in ('owner', 'admin'),
    'freeTextStored', false,
    'rawIpStored', false,
    'sessionReplayStored', false,
    'userIdentityReturned', false,
    'financeContentStored', false,
    'providerPayloadStored', false,
    'counts', jsonb_build_object(
      'open', (select count(*)::bigint from private.platform_security_incidents where status = 'open'),
      'acknowledged', (select count(*)::bigint from private.platform_security_incidents where status = 'acknowledged'),
      'investigating', (select count(*)::bigint from private.platform_security_incidents where status = 'investigating'),
      'monitoring', (select count(*)::bigint from private.platform_security_incidents where status = 'monitoring'),
      'criticalOpen', (
        select count(*)::bigint
        from private.platform_security_incidents
        where severity = 'critical' and status not in ('resolved', 'dismissed')
      ),
      'overdueOpen', (
        select count(*)::bigint
        from private.platform_security_incidents
        where due_at < now() and status not in ('resolved', 'dismissed')
      ),
      'resolved30d', (
        select count(*)::bigint
        from private.platform_security_incidents
        where status = 'resolved' and resolved_at >= now() - interval '30 days'
      ),
      'auditEvents30d', (
        select count(*)::bigint
        from private.platform_security_incident_audit
        where created_at >= now() - interval '30 days'
      ),
      'expiredAuditPending', (
        select count(*)::bigint
        from private.platform_security_incident_audit
        where expires_at <= now()
      ),
      'expiredIncidentsPending', (
        select count(*)::bigint
        from private.platform_security_incidents
        where expires_at is not null and expires_at <= now()
      )
    ),
    'queue', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'incidentCode', rows.incident_code,
          'category', rows.category,
          'severity', rows.severity,
          'status', rows.status,
          'source', rows.source,
          'sourceReference', rows.source_reference,
          'createdAt', rows.created_at,
          'dueAt', rows.due_at,
          'assigned', rows.assigned_to is not null,
          'assignedToMe', rows.assigned_to = v_actor,
          'overdue', rows.due_at is not null and rows.due_at < now(),
          'manageable', (
            v_actor_role = 'owner'
            or rows.assigned_to is null
            or rows.assigned_to = v_actor
          )
        ) order by
          case rows.severity
            when 'critical' then 1
            when 'high' then 2
            when 'medium' then 3
            else 4
          end,
          rows.due_at nulls last,
          rows.created_at desc
      )
      from (
        select *
        from private.platform_security_incidents
        where status not in ('resolved', 'dismissed')
        order by
          case severity
            when 'critical' then 1
            when 'high' then 2
            when 'medium' then 3
            else 4
          end,
          due_at nulls last,
          created_at desc
        limit 40
      ) rows
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function private.get_platform_security_incident_snapshot()
  from public, anon;
grant execute on function private.get_platform_security_incident_snapshot()
  to authenticated;

create or replace function private.purge_expired_platform_security_incidents()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
declare
  v_audit_deleted bigint := 0;
  v_incidents_deleted bigint := 0;
begin
  if current_user <> 'service_role' and session_user <> 'service_role' then
    raise exception 'service_role_required' using errcode = '42501';
  end if;

  delete from private.platform_security_incident_audit
  where expires_at <= now();
  get diagnostics v_audit_deleted = row_count;

  delete from private.platform_security_incidents
  where expires_at is not null and expires_at <= now();
  get diagnostics v_incidents_deleted = row_count;

  return jsonb_build_object(
    'auditRowsDeleted', v_audit_deleted,
    'incidentRowsDeleted', v_incidents_deleted
  );
end;
$$;

revoke all on function private.purge_expired_platform_security_incidents()
  from public, anon, authenticated;
grant execute on function private.purge_expired_platform_security_incidents()
  to service_role;

create or replace function public.get_platform_admin_snapshot()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot()
    || jsonb_build_object('access', private.get_admin_access_snapshot())
    || jsonb_build_object('userOperations', private.get_admin_user_operations_snapshot())
    || jsonb_build_object('incidents', private.get_platform_security_incident_snapshot());
$$;

revoke all on function public.get_platform_admin_snapshot()
  from public, anon;
grant execute on function public.get_platform_admin_snapshot()
  to authenticated;

commit;
