begin;

create table if not exists private.admin_compliance_audit_reviews (
  event_code text primary key,
  domain text not null,
  status text not null,
  source_digest bytea not null,
  reviewed_by uuid not null references auth.users(id) on delete restrict,
  reviewed_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint admin_compliance_audit_reviews_code_check check (
    event_code ~ '^AUD-[A-F0-9]{12}$'
  ),
  constraint admin_compliance_audit_reviews_domain_check check (
    domain in ('privacy', 'billing', 'access', 'incident')
  ),
  constraint admin_compliance_audit_reviews_status_check check (
    status in ('reviewed', 'flagged')
  ),
  constraint admin_compliance_audit_reviews_digest_check check (
    octet_length(source_digest) = 32
  ),
  constraint admin_compliance_audit_reviews_expiry_check check (
    expires_at > reviewed_at
  )
);

comment on table private.admin_compliance_audit_reviews is
  'Review overlay for structured Admin Panel audit events. Stores opaque event codes, controlled review status and source digests only; no user identity, finance content, free text, raw logs or provider payloads.';

create table if not exists private.admin_compliance_review_audit (
  id bigint generated by default as identity primary key,
  event_code text not null,
  domain text not null,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  previous_status text not null,
  next_status text not null,
  source_digest bytea not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint admin_compliance_review_audit_code_check check (
    event_code ~ '^AUD-[A-F0-9]{12}$'
  ),
  constraint admin_compliance_review_audit_domain_check check (
    domain in ('privacy', 'billing', 'access', 'incident')
  ),
  constraint admin_compliance_review_audit_previous_check check (
    previous_status in ('pending', 'reviewed', 'flagged')
  ),
  constraint admin_compliance_review_audit_next_check check (
    next_status in ('pending', 'reviewed', 'flagged')
  ),
  constraint admin_compliance_review_audit_digest_check check (
    octet_length(source_digest) = 32
  ),
  constraint admin_compliance_review_audit_expiry_check check (
    expires_at > created_at
  )
);

comment on table private.admin_compliance_review_audit is
  'Append-only review transition audit. Contains controlled status transitions and opaque event references only.';

alter table private.admin_compliance_audit_reviews enable row level security;
alter table private.admin_compliance_review_audit enable row level security;

revoke all on private.admin_compliance_audit_reviews,
  private.admin_compliance_review_audit
  from public, anon, authenticated;
revoke all on sequence private.admin_compliance_review_audit_id_seq
  from public, anon, authenticated;

drop policy if exists admin_compliance_audit_reviews_deny_direct
  on private.admin_compliance_audit_reviews;
create policy admin_compliance_audit_reviews_deny_direct
  on private.admin_compliance_audit_reviews
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists admin_compliance_review_audit_deny_direct
  on private.admin_compliance_review_audit;
create policy admin_compliance_review_audit_deny_direct
  on private.admin_compliance_review_audit
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.admin_compliance_audit_reviews,
  private.admin_compliance_review_audit
  to service_role;
grant usage, select on sequence private.admin_compliance_review_audit_id_seq
  to service_role;

create index if not exists admin_compliance_audit_reviews_status_idx
  on private.admin_compliance_audit_reviews (status, reviewed_at desc);
create index if not exists admin_compliance_audit_reviews_reviewer_idx
  on private.admin_compliance_audit_reviews (reviewed_by, reviewed_at desc);
create index if not exists admin_compliance_audit_reviews_expires_idx
  on private.admin_compliance_audit_reviews (expires_at);
create index if not exists admin_compliance_review_audit_event_idx
  on private.admin_compliance_review_audit (event_code, created_at desc);
create index if not exists admin_compliance_review_audit_actor_idx
  on private.admin_compliance_review_audit (actor_user_id, created_at desc);
create index if not exists admin_compliance_review_audit_expires_idx
  on private.admin_compliance_review_audit (expires_at);

create or replace function private.reject_platform_audit_update()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  raise exception 'platform_audit_rows_are_append_only' using errcode = '55000';
end;
$$;

revoke all on function private.reject_platform_audit_update()
  from public, anon, authenticated;
grant execute on function private.reject_platform_audit_update()
  to service_role;

drop trigger if exists privacy_request_audit_append_only
  on private.privacy_request_audit;
create trigger privacy_request_audit_append_only
  before update on private.privacy_request_audit
  for each row execute function private.reject_platform_audit_update();

drop trigger if exists billing_plan_audit_append_only
  on private.billing_plan_audit;
create trigger billing_plan_audit_append_only
  before update on private.billing_plan_audit
  for each row execute function private.reject_platform_audit_update();

drop trigger if exists platform_admin_access_audit_append_only
  on private.platform_admin_access_audit;
create trigger platform_admin_access_audit_append_only
  before update on private.platform_admin_access_audit
  for each row execute function private.reject_platform_audit_update();

drop trigger if exists platform_security_incident_audit_append_only
  on private.platform_security_incident_audit;
create trigger platform_security_incident_audit_append_only
  before update on private.platform_security_incident_audit
  for each row execute function private.reject_platform_audit_update();

drop trigger if exists admin_compliance_review_audit_append_only
  on private.admin_compliance_review_audit;
create trigger admin_compliance_review_audit_append_only
  before update on private.admin_compliance_review_audit
  for each row execute function private.reject_platform_audit_update();

create or replace function private.admin_compliance_event_code(
  p_domain text,
  p_source_id bigint
)
returns text
language sql
immutable
strict
set search_path = pg_catalog, extensions
as $$
  select 'AUD-' || upper(substr(
    encode(
      extensions.digest(
        convert_to(p_domain || ':' || p_source_id::text, 'UTF8'),
        'sha256'
      ),
      'hex'
    ),
    1,
    12
  ));
$$;

revoke all on function private.admin_compliance_event_code(text, bigint)
  from public, anon, authenticated;
grant execute on function private.admin_compliance_event_code(text, bigint)
  to service_role;

create or replace function private.admin_compliance_event_rows()
returns table (
  event_code text,
  domain text,
  action text,
  subject_reference text,
  occurred_at timestamptz,
  previous_state text,
  next_state text,
  attention_required boolean,
  event_digest bytea
)
language sql
stable
security definer
set search_path = pg_catalog, auth, private, extensions
as $$
  with normalized as (
    select
      a.id,
      'privacy'::text as domain,
      a.action,
      r.request_code as subject_reference,
      a.created_at as occurred_at,
      concat_ws(
        ' / ',
        nullif(a.previous_status, ''),
        nullif(a.previous_verification_status, '')
      ) as previous_state,
      concat_ws(
        ' / ',
        nullif(a.next_status, ''),
        nullif(a.next_verification_status, ''),
        case when a.assignment_changed then 'assignment changed' end
      ) as next_state,
      (
        a.next_status = 'rejected'
        or a.next_verification_status in ('failed', 'rejected')
      ) as attention_required
    from private.privacy_request_audit a
    join private.privacy_requests r on r.id = a.request_id

    union all

    select
      a.id,
      'billing'::text,
      a.action,
      a.plan_code,
      a.created_at,
      concat_ws(
        ' / ',
        nullif(a.before_billing_interval, ''),
        nullif(a.before_currency, ''),
        case
          when a.before_is_active is true then 'active'
          when a.before_is_active is false then 'inactive'
        end
      ),
      concat_ws(
        ' / ',
        nullif(a.after_billing_interval, ''),
        nullif(a.after_currency, ''),
        case
          when a.after_is_active is true then 'active'
          when a.after_is_active is false then 'inactive'
        end
      ),
      a.action = 'deactivated'
    from private.billing_plan_audit a

    union all

    select
      a.id,
      'access'::text,
      a.action,
      coalesce(
        i.invitation_code,
        case
          when a.subject_user_id is not null
            then private.platform_admin_reference(a.subject_user_id)
        end
      ),
      a.created_at,
      nullif(a.previous_role, ''),
      nullif(a.next_role, ''),
      a.action in ('invitation_accepted', 'role_changed', 'access_disabled')
    from private.platform_admin_access_audit a
    left join private.platform_admin_invitations i on i.id = a.invitation_id

    union all

    select
      a.id,
      'incident'::text,
      a.action,
      i.incident_code,
      a.created_at,
      concat_ws(
        ' / ',
        nullif(a.previous_status, ''),
        nullif(a.previous_severity, '')
      ),
      concat_ws(
        ' / ',
        nullif(a.next_status, ''),
        nullif(a.next_severity, ''),
        nullif(a.resolution_code, '')
      ),
      (
        a.next_severity = 'critical'
        or a.next_status = 'dismissed'
        or a.resolution_code = 'accepted_risk'
      )
    from private.platform_security_incident_audit a
    join private.platform_security_incidents i on i.id = a.incident_id
  )
  select
    private.admin_compliance_event_code(n.domain, n.id),
    n.domain,
    n.action,
    n.subject_reference,
    n.occurred_at,
    nullif(n.previous_state, ''),
    nullif(n.next_state, ''),
    n.attention_required,
    extensions.digest(
      convert_to(
        jsonb_build_object(
          'domain', n.domain,
          'action', n.action,
          'subjectReference', n.subject_reference,
          'occurredAt', n.occurred_at,
          'previousState', nullif(n.previous_state, ''),
          'nextState', nullif(n.next_state, ''),
          'attentionRequired', n.attention_required
        )::text,
        'UTF8'
      ),
      'sha256'
    )
  from normalized n;
$$;

revoke all on function private.admin_compliance_event_rows()
  from public, anon, authenticated;
grant execute on function private.admin_compliance_event_rows()
  to service_role;

create or replace function private.get_admin_compliance_audit_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'operationsAllowed', v_actor_role in ('owner', 'admin'),
    'mode', case
      when v_actor_role in ('owner', 'admin') then 'review'
      else 'read_only'
    end,
    'appendOnlySources', true,
    'sourceDigestVerification', true,
    'rawIdentityReturned', false,
    'financeContentReturned', false,
    'rawLogsReturned', false,
    'providerPayloadReturned', false,
    'counts', jsonb_build_object(
      'events30d', (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        where e.occurred_at >= now() - interval '30 days'
      ),
      'pending30d', (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        left join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        where e.occurred_at >= now() - interval '30 days'
          and r.event_code is null
      ),
      'reviewed30d', (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        where e.occurred_at >= now() - interval '30 days'
          and r.status = 'reviewed'
      ),
      'flagged30d', (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        where e.occurred_at >= now() - interval '30 days'
          and r.status = 'flagged'
      ),
      'attentionPending', (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        left join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        where e.attention_required and r.event_code is null
      ),
      'integrityMismatches', (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        where r.source_digest <> e.event_digest
      ),
      'reviewTransitions30d', (
        select count(*)::bigint
        from private.admin_compliance_review_audit
        where created_at >= now() - interval '30 days'
      ),
      'expiredReviewsPending', (
        select count(*)::bigint
        from private.admin_compliance_audit_reviews
        where expires_at <= now()
      ),
      'expiredReviewAuditPending', (
        select count(*)::bigint
        from private.admin_compliance_review_audit
        where expires_at <= now()
      )
    ),
    'timeline', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'eventCode', rows.event_code,
          'domain', rows.domain,
          'action', rows.action,
          'subjectReference', rows.subject_reference,
          'occurredAt', rows.occurred_at,
          'previousState', rows.previous_state,
          'nextState', rows.next_state,
          'attentionRequired', rows.attention_required,
          'reviewStatus', coalesce(rows.review_status, 'pending'),
          'reviewedAt', rows.reviewed_at,
          'integrityState', case
            when rows.review_status is null then 'unverified'
            when rows.source_digest = rows.event_digest then 'verified'
            else 'mismatch'
          end
        ) order by rows.occurred_at desc, rows.event_code
      )
      from (
        select
          e.*,
          r.status as review_status,
          r.reviewed_at,
          r.source_digest
        from private.admin_compliance_event_rows() e
        left join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        order by e.occurred_at desc, e.event_code
        limit 60
      ) rows
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function private.get_admin_compliance_audit_snapshot()
  from public, anon;
grant execute on function private.get_admin_compliance_audit_snapshot()
  to authenticated;

create or replace function private.apply_admin_compliance_review(
  p_event_code text,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_event record;
  v_previous_status text := 'pending';
  v_event_code text := upper(trim(coalesce(p_event_code, '')));
  v_status text := lower(trim(coalesce(p_status, '')));
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role not in ('owner', 'admin') then
    raise exception 'compliance_review_access_required' using errcode = '42501';
  end if;

  if v_event_code !~ '^AUD-[A-F0-9]{12}$' then
    raise exception 'compliance_event_code_invalid' using errcode = '22023';
  end if;

  if v_status not in ('pending', 'reviewed', 'flagged') then
    raise exception 'compliance_review_status_invalid' using errcode = '22023';
  end if;

  select * into v_event
  from private.admin_compliance_event_rows()
  where event_code = v_event_code;

  if not found then
    raise exception 'compliance_event_not_found' using errcode = 'P0002';
  end if;

  select status into v_previous_status
  from private.admin_compliance_audit_reviews
  where event_code = v_event_code
  for update;

  v_previous_status := coalesce(v_previous_status, 'pending');

  if v_status = 'pending' then
    delete from private.admin_compliance_audit_reviews
    where event_code = v_event_code;
  else
    insert into private.admin_compliance_audit_reviews (
      event_code,
      domain,
      status,
      source_digest,
      reviewed_by,
      reviewed_at,
      expires_at
    ) values (
      v_event.event_code,
      v_event.domain,
      v_status,
      v_event.event_digest,
      v_actor,
      now(),
      now() + interval '24 months'
    )
    on conflict (event_code) do update
    set domain = excluded.domain,
        status = excluded.status,
        source_digest = excluded.source_digest,
        reviewed_by = excluded.reviewed_by,
        reviewed_at = excluded.reviewed_at,
        expires_at = excluded.expires_at;
  end if;

  if v_previous_status <> v_status then
    insert into private.admin_compliance_review_audit (
      event_code,
      domain,
      actor_user_id,
      previous_status,
      next_status,
      source_digest
    ) values (
      v_event.event_code,
      v_event.domain,
      v_actor,
      v_previous_status,
      v_status,
      v_event.event_digest
    );
  end if;

  return jsonb_build_object(
    'eventCode', v_event.event_code,
    'status', v_status,
    'updated', true
  );
end;
$$;

create or replace function public.apply_admin_compliance_review(
  p_event_code text,
  p_status text
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.apply_admin_compliance_review(p_event_code, p_status);
$$;

revoke all on function private.apply_admin_compliance_review(text, text)
  from public, anon;
grant execute on function private.apply_admin_compliance_review(text, text)
  to authenticated;
revoke all on function public.apply_admin_compliance_review(text, text)
  from public, anon;
grant execute on function public.apply_admin_compliance_review(text, text)
  to authenticated;

create or replace function private.purge_expired_admin_compliance_reviews()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
declare
  v_reviews_deleted bigint := 0;
  v_audit_deleted bigint := 0;
begin
  delete from private.admin_compliance_review_audit
  where expires_at <= now();
  get diagnostics v_audit_deleted = row_count;

  delete from private.admin_compliance_audit_reviews
  where expires_at <= now();
  get diagnostics v_reviews_deleted = row_count;

  return jsonb_build_object(
    'reviewRowsDeleted', v_reviews_deleted,
    'auditRowsDeleted', v_audit_deleted
  );
end;
$$;

revoke all on function private.purge_expired_admin_compliance_reviews()
  from public, anon, authenticated;
grant execute on function private.purge_expired_admin_compliance_reviews()
  to service_role;

create or replace function public.get_platform_admin_snapshot()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot()
    || jsonb_build_object('access', private.get_admin_access_snapshot())
    || jsonb_build_object('userOperations', private.get_admin_user_operations_snapshot())
    || jsonb_build_object('incidents', private.get_platform_security_incident_snapshot())
    || jsonb_build_object('complianceAudit', private.get_admin_compliance_audit_snapshot());
$$;

revoke all on function public.get_platform_admin_snapshot()
  from public, anon;
grant execute on function public.get_platform_admin_snapshot()
  to authenticated;

commit;
