begin;

create table if not exists private.admin_release_approvals (
  release_code text primary key default (
    'REL-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))
  ),
  revision_sha text not null,
  environment text not null,
  readiness_digest bytea not null,
  approved_by uuid not null references auth.users(id) on delete restrict,
  approved_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  revoked_at timestamptz,
  constraint admin_release_approvals_code_check check (
    release_code ~ '^REL-[A-F0-9]{12}$'
  ),
  constraint admin_release_approvals_revision_check check (
    revision_sha ~ '^[a-f0-9]{40}$'
  ),
  constraint admin_release_approvals_environment_check check (
    environment in ('production', 'preview')
  ),
  constraint admin_release_approvals_digest_check check (
    octet_length(readiness_digest) = 32
  ),
  constraint admin_release_approvals_expiry_check check (
    expires_at > approved_at
    and expires_at <= approved_at + interval '24 hours'
  ),
  constraint admin_release_approvals_revocation_check check (
    revoked_at is null or revoked_at >= approved_at
  )
);

comment on table private.admin_release_approvals is
  'Short-lived Owner approvals for an exact deployment revision and database readiness digest. Stores no free text, user identity output, finance content, runtime secret or provider payload.';

create table if not exists private.admin_release_approval_audit (
  id bigint generated by default as identity primary key,
  release_code text not null,
  revision_sha text not null,
  environment text not null,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  readiness_digest bytea not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 months'),
  constraint admin_release_approval_audit_code_check check (
    release_code ~ '^REL-[A-F0-9]{12}$'
  ),
  constraint admin_release_approval_audit_revision_check check (
    revision_sha ~ '^[a-f0-9]{40}$'
  ),
  constraint admin_release_approval_audit_environment_check check (
    environment in ('production', 'preview')
  ),
  constraint admin_release_approval_audit_action_check check (
    action in ('approved', 'revoked', 'superseded')
  ),
  constraint admin_release_approval_audit_digest_check check (
    octet_length(readiness_digest) = 32
  ),
  constraint admin_release_approval_audit_expiry_check check (
    expires_at > created_at
  )
);

comment on table private.admin_release_approval_audit is
  'Append-only release approval transitions with 24-month retention and no free text or sensitive user data.';

alter table private.admin_release_approvals enable row level security;
alter table private.admin_release_approval_audit enable row level security;

revoke all on private.admin_release_approvals,
  private.admin_release_approval_audit
  from public, anon, authenticated;
revoke all on sequence private.admin_release_approval_audit_id_seq
  from public, anon, authenticated;

drop policy if exists admin_release_approvals_deny_direct
  on private.admin_release_approvals;
create policy admin_release_approvals_deny_direct
  on private.admin_release_approvals
  for all
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists admin_release_approval_audit_deny_direct
  on private.admin_release_approval_audit;
create policy admin_release_approval_audit_deny_direct
  on private.admin_release_approval_audit
  for all
  to anon, authenticated
  using (false)
  with check (false);

grant select, insert, update, delete
  on private.admin_release_approvals,
  private.admin_release_approval_audit
  to service_role;
grant usage, select on sequence private.admin_release_approval_audit_id_seq
  to service_role;

create index if not exists admin_release_approvals_revision_environment_idx
  on private.admin_release_approvals (revision_sha, environment, approved_at desc);
create index if not exists admin_release_approvals_expires_idx
  on private.admin_release_approvals (expires_at)
  where revoked_at is null;
create index if not exists admin_release_approval_audit_release_idx
  on private.admin_release_approval_audit (release_code, created_at desc);
create index if not exists admin_release_approval_audit_actor_idx
  on private.admin_release_approval_audit (actor_user_id, created_at desc);
create index if not exists admin_release_approval_audit_expires_idx
  on private.admin_release_approval_audit (expires_at);

drop trigger if exists admin_release_approval_audit_append_only
  on private.admin_release_approval_audit;
create trigger admin_release_approval_audit_append_only
  before update on private.admin_release_approval_audit
  for each row execute function private.reject_platform_audit_update();

create or replace function private.admin_release_database_state()
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, auth, private, billing, telemetry, supabase_migrations
as $$
  with required_migrations(name) as (
    values
      ('privacy_governance_control_center'::text),
      ('privacy_request_operations'),
      ('billing_plan_operations'),
      ('admin_team_access_security'),
      ('admin_user_account_operations'),
      ('admin_incident_alert_operations'),
      ('harden_admin_incident_operations'),
      ('require_incident_resolution_code'),
      ('index_incident_foreign_keys'),
      ('admin_compliance_audit_review_center'),
      ('admin_release_readiness_center')
  ),
  required_tables(name) as (
    values
      ('private.platform_admins'::text),
      ('private.platform_admin_invitations'),
      ('private.platform_admin_access_audit'),
      ('private.privacy_requests'),
      ('private.privacy_request_audit'),
      ('private.platform_security_incidents'),
      ('private.platform_security_incident_audit'),
      ('private.admin_compliance_audit_reviews'),
      ('private.admin_compliance_review_audit'),
      ('private.admin_release_approvals'),
      ('private.admin_release_approval_audit')
  ),
  required_triggers(name) as (
    values
      ('privacy_request_audit_append_only'::text),
      ('billing_plan_audit_append_only'),
      ('platform_admin_access_audit_append_only'),
      ('platform_security_incident_audit_append_only'),
      ('admin_compliance_review_audit_append_only'),
      ('admin_release_approval_audit_append_only')
  ),
  required_functions(signature) as (
    values
      ('public.get_platform_admin_snapshot()'::text),
      ('private.get_admin_release_readiness_snapshot()'),
      ('public.approve_admin_release(text,text)'),
      ('public.revoke_admin_release(text)'),
      ('private.purge_expired_admin_release_approvals()'),
      ('private.admin_release_database_state()'),
      ('private.admin_release_database_state_digest()'),
      ('private.get_admin_compliance_audit_snapshot()')
  ),
  permission_checks(passed) as (
    values
      (not has_function_privilege('anon', 'public.get_platform_admin_snapshot()', 'execute')),
      (not has_function_privilege('anon', 'public.approve_admin_release(text,text)', 'execute')),
      (not has_function_privilege('anon', 'public.revoke_admin_release(text)', 'execute')),
      (not has_function_privilege('authenticated', 'private.purge_expired_admin_release_approvals()', 'execute')),
      (not has_function_privilege('authenticated', 'private.purge_expired_admin_compliance_reviews()', 'execute')),
      (not has_function_privilege('authenticated', 'private.purge_expired_platform_security_incidents()', 'execute')),
      (not has_function_privilege('anon', 'public.apply_admin_compliance_review(text,text)', 'execute')),
      (not has_function_privilege('anon', 'public.apply_platform_security_incident_workflow(text,text,text,timestamptz,boolean,text)', 'execute'))
  ),
  controls as (
    select
      (select count(*)::bigint from required_migrations) as migrations_total,
      (
        select count(*)::bigint
        from required_migrations r
        where exists (
          select 1
          from supabase_migrations.schema_migrations m
          where m.name = r.name
        )
      ) as migrations_applied,
      (select count(*)::bigint from required_tables) as rls_total,
      (
        select count(*)::bigint
        from required_tables r
        where coalesce((
          select c.relrowsecurity
          from pg_class c
          where c.oid = to_regclass(r.name)
        ), false)
      ) as rls_protected,
      (select count(*)::bigint from required_tables) as direct_access_total,
      (
        select count(*)::bigint
        from required_tables r
        where to_regclass(r.name) is not null
          and not has_table_privilege('anon', r.name, 'select')
          and not has_table_privilege('authenticated', r.name, 'select')
      ) as direct_access_denied,
      (select count(*)::bigint from required_triggers) as append_only_expected,
      (
        select count(*)::bigint
        from required_triggers r
        where exists (
          select 1
          from pg_trigger t
          where not t.tgisinternal and t.tgname = r.name
        )
      ) as append_only_present,
      (select count(*)::bigint from required_functions) as functions_total,
      (
        select count(*)::bigint
        from required_functions r
        where to_regprocedure(r.signature) is not null
      ) as functions_present,
      (select count(*)::bigint from permission_checks) as permissions_total,
      (select count(*)::bigint from permission_checks where passed) as permissions_passed
  ),
  blockers as (
    select
      (
        select count(*)::bigint
        from private.privacy_requests
        where status in ('pending', 'identity_verification', 'in_progress')
          and due_at < now()
      ) as overdue_privacy,
      (
        select count(*)::bigint
        from private.platform_security_incidents
        where severity = 'critical'
          and status not in ('resolved', 'dismissed')
      ) as critical_incidents,
      (
        select count(*)::bigint
        from private.platform_security_incidents
        where due_at < now()
          and status not in ('resolved', 'dismissed')
      ) as overdue_incidents,
      (
        select count(*)::bigint
        from private.admin_compliance_event_rows() e
        join private.admin_compliance_audit_reviews r
          on r.event_code = e.event_code
        where r.source_digest <> e.event_digest
      ) as integrity_mismatches,
      (
        select count(*)::bigint
        from billing.webhook_events
        where processing_status = 'failed'
          and received_at >= now() - interval '24 hours'
      ) as failed_webhooks_24h,
      (
        select count(*)::bigint
        from telemetry.events
        where result = 'failed'
          and occurred_at >= now() - interval '7 days'
      ) as failed_operations_7d,
      (
        select count(*)::bigint
        from private.platform_admins
        where role = 'owner' and disabled_at is null
      ) as active_owners
  )
  select jsonb_build_object(
    'database', jsonb_build_object(
      'requiredMigrationsApplied', c.migrations_applied,
      'requiredMigrationsTotal', c.migrations_total,
      'rlsTablesProtected', c.rls_protected,
      'rlsTablesTotal', c.rls_total,
      'directAccessDenied', c.direct_access_denied,
      'directAccessChecksTotal', c.direct_access_total,
      'appendOnlyTriggers', c.append_only_present,
      'appendOnlyTriggersExpected', c.append_only_expected,
      'requiredFunctionsPresent', c.functions_present,
      'requiredFunctionsTotal', c.functions_total,
      'permissionChecksPassed', c.permissions_passed,
      'permissionChecksTotal', c.permissions_total
    ),
    'blockers', jsonb_build_object(
      'overduePrivacy', b.overdue_privacy,
      'criticalIncidents', b.critical_incidents,
      'overdueIncidents', b.overdue_incidents,
      'integrityMismatches', b.integrity_mismatches,
      'failedWebhooks24h', b.failed_webhooks_24h,
      'failedOperations7d', b.failed_operations_7d,
      'activeOwners', b.active_owners
    )
  )
  from controls c cross join blockers b;
$$;

revoke all on function private.admin_release_database_state()
  from public, anon, authenticated;
grant execute on function private.admin_release_database_state()
  to service_role;

create or replace function private.admin_release_database_state_digest()
returns bytea
language sql
stable
security definer
set search_path = pg_catalog, private, extensions
as $$
  select extensions.digest(
    convert_to(private.admin_release_database_state()::text, 'UTF8'),
    'sha256'
  );
$$;

revoke all on function private.admin_release_database_state_digest()
  from public, anon, authenticated;
grant execute on function private.admin_release_database_state_digest()
  to service_role;

create or replace function private.get_admin_release_readiness_snapshot()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_state jsonb;
  v_digest bytea;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role is null then
    raise exception 'admin_access_required' using errcode = '42501';
  end if;

  v_state := private.admin_release_database_state();
  v_digest := private.admin_release_database_state_digest();

  return jsonb_build_object(
    'approvalAllowed', v_actor_role = 'owner',
    'mode', case when v_actor_role = 'owner' then 'approve' else 'read_only' end,
    'approvalRetentionMonths', 24,
    'approvalValidityHours', 24,
    'rawIdentityReturned', false,
    'financeContentReturned', false,
    'runtimeSecretsStored', false,
    'freeTextStored', false,
    'database', v_state->'database',
    'approvals', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'releaseCode', rows.release_code,
          'revisionSha', rows.revision_sha,
          'environment', rows.environment,
          'status', case
            when rows.revoked_at is not null then 'revoked'
            when rows.expires_at <= now() then 'expired'
            else 'active'
          end,
          'databaseState', case
            when rows.readiness_digest = v_digest then 'verified'
            else 'stale'
          end,
          'approvedAt', rows.approved_at,
          'expiresAt', rows.expires_at,
          'revokedAt', rows.revoked_at
        ) order by rows.approved_at desc
      )
      from (
        select *
        from private.admin_release_approvals
        order by approved_at desc
        limit 10
      ) rows
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function private.get_admin_release_readiness_snapshot()
  from public, anon;
grant execute on function private.get_admin_release_readiness_snapshot()
  to authenticated;

create or replace function private.approve_admin_release(
  p_revision_sha text,
  p_environment text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_revision_sha text := lower(trim(coalesce(p_revision_sha, '')));
  v_environment text := lower(trim(coalesce(p_environment, '')));
  v_state jsonb;
  v_digest bytea;
  v_release private.admin_release_approvals%rowtype;
  v_superseded private.admin_release_approvals%rowtype;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role <> 'owner' then
    raise exception 'owner_release_approval_required' using errcode = '42501';
  end if;

  if v_revision_sha !~ '^[a-f0-9]{40}$' then
    raise exception 'release_revision_invalid' using errcode = '22023';
  end if;

  if v_environment not in ('production', 'preview') then
    raise exception 'release_environment_invalid' using errcode = '22023';
  end if;

  v_state := private.admin_release_database_state();

  if (v_state->'database'->>'requiredMigrationsApplied')::bigint
      <> (v_state->'database'->>'requiredMigrationsTotal')::bigint
    or (v_state->'database'->>'rlsTablesProtected')::bigint
      <> (v_state->'database'->>'rlsTablesTotal')::bigint
    or (v_state->'database'->>'directAccessDenied')::bigint
      <> (v_state->'database'->>'directAccessChecksTotal')::bigint
    or (v_state->'database'->>'appendOnlyTriggers')::bigint
      <> (v_state->'database'->>'appendOnlyTriggersExpected')::bigint
    or (v_state->'database'->>'requiredFunctionsPresent')::bigint
      <> (v_state->'database'->>'requiredFunctionsTotal')::bigint
    or (v_state->'database'->>'permissionChecksPassed')::bigint
      <> (v_state->'database'->>'permissionChecksTotal')::bigint
    or (v_state->'blockers'->>'overduePrivacy')::bigint > 0
    or (v_state->'blockers'->>'criticalIncidents')::bigint > 0
    or (v_state->'blockers'->>'overdueIncidents')::bigint > 0
    or (v_state->'blockers'->>'integrityMismatches')::bigint > 0
    or (v_state->'blockers'->>'failedWebhooks24h')::bigint > 0
    or (v_state->'blockers'->>'failedOperations7d')::bigint > 0
    or (v_state->'blockers'->>'activeOwners')::bigint < 1 then
    raise exception 'release_readiness_blocked' using errcode = '55000';
  end if;

  v_digest := private.admin_release_database_state_digest();

  for v_superseded in
    update private.admin_release_approvals
    set revoked_at = now()
    where revoked_at is null and expires_at > now()
    returning *
  loop
    insert into private.admin_release_approval_audit (
      release_code,
      revision_sha,
      environment,
      actor_user_id,
      action,
      readiness_digest
    ) values (
      v_superseded.release_code,
      v_superseded.revision_sha,
      v_superseded.environment,
      v_actor,
      'superseded',
      v_superseded.readiness_digest
    );
  end loop;

  insert into private.admin_release_approvals (
    revision_sha,
    environment,
    readiness_digest,
    approved_by,
    approved_at,
    expires_at
  ) values (
    v_revision_sha,
    v_environment,
    v_digest,
    v_actor,
    now(),
    now() + interval '24 hours'
  ) returning * into v_release;

  insert into private.admin_release_approval_audit (
    release_code,
    revision_sha,
    environment,
    actor_user_id,
    action,
    readiness_digest
  ) values (
    v_release.release_code,
    v_release.revision_sha,
    v_release.environment,
    v_actor,
    'approved',
    v_release.readiness_digest
  );

  return jsonb_build_object(
    'releaseCode', v_release.release_code,
    'revisionSha', v_release.revision_sha,
    'environment', v_release.environment,
    'approved', true,
    'expiresAt', v_release.expires_at
  );
end;
$$;

create or replace function public.approve_admin_release(
  p_revision_sha text,
  p_environment text
)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.approve_admin_release(p_revision_sha, p_environment);
$$;

revoke all on function private.approve_admin_release(text, text)
  from public, anon;
grant execute on function private.approve_admin_release(text, text)
  to authenticated;
revoke all on function public.approve_admin_release(text, text)
  from public, anon;
grant execute on function public.approve_admin_release(text, text)
  to authenticated;

create or replace function private.revoke_admin_release(p_release_code text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, auth, private
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_role text;
  v_release_code text := upper(trim(coalesce(p_release_code, '')));
  v_release private.admin_release_approvals%rowtype;
begin
  select role into v_actor_role
  from private.platform_admins
  where user_id = v_actor and disabled_at is null;

  if v_actor is null or v_actor_role <> 'owner' then
    raise exception 'owner_release_approval_required' using errcode = '42501';
  end if;

  if v_release_code !~ '^REL-[A-F0-9]{12}$' then
    raise exception 'release_code_invalid' using errcode = '22023';
  end if;

  update private.admin_release_approvals
  set revoked_at = now()
  where release_code = v_release_code
    and revoked_at is null
    and expires_at > now()
  returning * into v_release;

  if not found then
    raise exception 'release_approval_not_found' using errcode = 'P0002';
  end if;

  insert into private.admin_release_approval_audit (
    release_code,
    revision_sha,
    environment,
    actor_user_id,
    action,
    readiness_digest
  ) values (
    v_release.release_code,
    v_release.revision_sha,
    v_release.environment,
    v_actor,
    'revoked',
    v_release.readiness_digest
  );

  return jsonb_build_object(
    'releaseCode', v_release.release_code,
    'revoked', true
  );
end;
$$;

create or replace function public.revoke_admin_release(p_release_code text)
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.revoke_admin_release(p_release_code);
$$;

revoke all on function private.revoke_admin_release(text)
  from public, anon;
grant execute on function private.revoke_admin_release(text)
  to authenticated;
revoke all on function public.revoke_admin_release(text)
  from public, anon;
grant execute on function public.revoke_admin_release(text)
  to authenticated;

create or replace function private.purge_expired_admin_release_approvals()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
declare
  v_approvals_deleted bigint := 0;
  v_audit_deleted bigint := 0;
begin
  delete from private.admin_release_approval_audit
  where expires_at <= now();
  get diagnostics v_audit_deleted = row_count;

  delete from private.admin_release_approvals
  where expires_at <= now() - interval '24 months';
  get diagnostics v_approvals_deleted = row_count;

  return jsonb_build_object(
    'approvalRowsDeleted', v_approvals_deleted,
    'auditRowsDeleted', v_audit_deleted
  );
end;
$$;

revoke all on function private.purge_expired_admin_release_approvals()
  from public, anon, authenticated;
grant execute on function private.purge_expired_admin_release_approvals()
  to service_role;

create or replace function public.get_platform_admin_snapshot()
returns jsonb
language sql
security invoker
set search_path = pg_catalog, private
as $$
  select private.get_platform_admin_snapshot()
    || jsonb_build_object('access', private.get_admin_access_snapshot())
    || jsonb_build_object('userOperations', private.get_admin_user_operations_snapshot())
    || jsonb_build_object('incidents', private.get_platform_security_incident_snapshot())
    || jsonb_build_object('complianceAudit', private.get_admin_compliance_audit_snapshot())
    || jsonb_build_object('releaseReadiness', private.get_admin_release_readiness_snapshot());
$$;

revoke all on function public.get_platform_admin_snapshot()
  from public, anon;
grant execute on function public.get_platform_admin_snapshot()
  to authenticated;

commit;
